### ISSUE TITLE
Water Leakage Sensor DCH-S160 support

### ISSUE THREAD

**Issue by Molodax** [UpDryTwist/dlink-dchs150-hass#56]
**Is your feature request related to a problem? Please describe.**
Thanks a lot for bringing to life the motion sensor DCH-S150! It works flawless for me.

**Describe the solution you'd like**
There is another device from the same family: Water Leakage Sensor DCH-S160.
It is so similar that your interpretation even allows to pair with it.
What does not work, is of course settings.

*Describe alternatives you've considered**
There is no alternative except your solution. 

**Additional context**
I can provide logs or whatever you'd be needed to make it happen. 
Add any other context or screenshots about the

**Comment by UpDryTwist** [comment]
I ordered one to see how straightforward it'll be.  The problem is that the D-Link API isn't specified anywhere, and with the D-Link servers down, there's not much way to intercept and reverse engineer it.  I'll have to poke around to see if there are any examples out there from back when it was working.

**Comment by Molodax** [comment]
> I ordered one to see how straightforward it'll be. The problem is that the D-Link API isn't specified anywhere, and with the D-Link servers down, there's not much way to intercept and reverse engineer it. I'll have to poke around to see if there are any examples out there from back when it was working.
Thanks for looking into this!
Actually, postlund had support for both devices https://github.com/postlund/dlink_hnap
Not sure if can be helpful in any way but 🫰

**Comment by UpDryTwist** [comment]
@Molodax - this isn't forgotten.  My sensor arrived; I just haven't had time to tinker with this yet.  As the weather turns to Fall, I'll not be outside all weekend, so . . . "soon" . . . ;)

**Comment by Molodax** [comment]
Just wondering if there is still thinking to try supporting DCH-S160. And if yes, let me know if I can help you in any way. Thanks.

**Comment by UpDryTwist** [comment]
Mea culpa; it's still sitting on my desk as a project, just haven't gotten to it yet.  Still intend to.  Sorry for the delay!

**Comment by UpDryTwist** [comment]
OK.  Added support.  Should "just work" if you add it as you would have added a motion detector.  Reopen this issue if you run into any errors, but it seems to be working fine for me.

**Comment by Molodax** [comment]
> OK. Added support. Should "just work" if you add it as you would have added a motion detector. Reopen this issue if you run into any errors, but it seems to be working fine for me.

Many thanks!
It does work 🙂
