### ISSUE TITLE
Not reaload if device is off

### ISSUE THREAD

**Issue by Marmoulak** [UpDryTwist/dlink-dchs150-hass#66]
## Version of the custom_component
newest version
Home Assistant 2023.9.2
Supervisor 2023.09.2 
Operating System 10.5 
Frontend 20230911.0 - latest 

## Configuration

```yaml
Add your logs here.
```

## Describe the bug

Hi
Thanks for your nice works. 
When HS restarts and some of my dchs150 are offline, they get "failed to setup" even when they are online again. I have to reload them manually to get them back. 
Can you please help?  

## Debug log

```text

Add your logs here.

```
![image](https://github.com/UpDryTwist/dlink-dchs150-hass/assets/44494190/3759874a-35df-4db4-afb0-fa2d1fbb85d7)

**Comment by UpDryTwist** [comment]
Yeah, that's irritating; happens to me, too (I just restart HASS when that happens).  I made an update today that _might_ fix it (anyhow, it fixes a start-up error), but haven't tested it yet for this particular case.  I'll try to test this when I get around to adding in the water sensor.

**Comment by UpDryTwist** [comment]
Made another update.  Tested.  Works fine for me.  Reopen if not working for you.
